/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import React, { useState } from 'react';
import { 
  Microscope, 
  Stethoscope, 
  FlaskConical, 
  Leaf, 
  Utensils, 
  ChevronDown, 
  FolderHeart, 
  Search, 
  Bell, 
  Rss, 
  Calendar, 
  Globe, 
  BarChart3, 
  ArrowLeftRight, 
  Download,
  AlertCircle,
  ShieldCheck,
  FileText,
  XCircle,
  CheckCircle2,
  Info,
  X,
  Wheat,
  Drumstick,
  Carrot,
  Apple,
  Milk,
  CakeSlice
} from 'lucide-react';
import { motion } from 'motion/react';

const SidebarItem = ({ icon: Icon, label, active = false, onClick }: { icon: any, label: string, active?: boolean, onClick?: () => void }) => (
  <button 
    onClick={onClick}
    className={`w-full flex items-center gap-3 px-3 py-2.5 rounded-lg transition-colors text-left ${
      active 
        ? 'bg-primary/10 text-primary' 
        : 'text-slate-600 dark:text-slate-400 hover:bg-slate-100 dark:hover:bg-slate-800'
    }`}
  >
    <Icon className="size-5" />
    <span className="text-sm font-medium">{label}</span>
  </button>
);

const NewsCard = ({ country, title, description, time, type, isNew = false }: { country: string, title: string, description: string, time: string, type: string, isNew?: boolean }) => (
  <motion.div 
    whileHover={{ y: -2 }}
    className="bg-white dark:bg-slate-900 p-4 rounded-xl border border-slate-200 dark:border-slate-800 hover:shadow-md transition-shadow cursor-pointer group relative"
  >
    {isNew && (
      <div className="absolute top-3 right-3 flex items-center gap-1.5">
        <div className="size-2 bg-red-500 rounded-full animate-pulse-red"></div>
        <span className="text-[9px] font-black text-red-500 tracking-tighter italic">LIVE</span>
      </div>
    )}
    <div className="flex items-start gap-4">
      <div className="size-10 rounded bg-slate-100 dark:bg-slate-800 flex items-center justify-center font-bold text-xs text-slate-600 dark:text-slate-400 flex-shrink-0">
        {country}
      </div>
      <div className="space-y-1">
        <h3 className="text-sm font-bold group-hover:text-primary transition-colors line-clamp-2">{title}</h3>
        <p className="text-xs text-slate-500 line-clamp-2">{description}</p>
        <p className="text-[10px] text-slate-400 mt-2">{time} • {type}</p>
      </div>
    </div>
  </motion.div>
);

const ReportSummaryModal = ({ isOpen, onClose }: { isOpen: boolean, onClose: () => void }) => {
  if (!isOpen) return null;
  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/50 backdrop-blur-sm">
      <motion.div 
        initial={{ opacity: 0, scale: 0.95 }}
        animate={{ opacity: 1, scale: 1 }}
        className="bg-white dark:bg-slate-900 w-full max-w-2xl rounded-2xl shadow-2xl overflow-hidden border border-slate-200 dark:border-slate-800"
      >
        <div className="p-6 border-b border-slate-100 dark:border-slate-800 flex items-center justify-between bg-slate-50/50 dark:bg-slate-800/50">
          <div className="flex items-center gap-3">
            <div className="size-10 bg-primary/10 rounded-lg flex items-center justify-center text-primary">
              <FileText className="size-6" />
            </div>
            <div>
              <h3 className="font-bold text-lg">R&D Impact Report Summary</h3>
              <p className="text-xs text-slate-500">Generated by AI Regulatory Engine v4.2</p>
            </div>
          </div>
          <div className="flex items-center gap-4">
            <div className="text-right">
              <p className="text-[10px] font-bold text-slate-400 uppercase">Regulatory Risk Score</p>
              <p className="text-xl font-black text-rose-500">85/100</p>
            </div>
            <button onClick={onClose} className="p-2 hover:bg-slate-200 dark:hover:bg-slate-700 rounded-full transition-colors">
              <X className="size-5" />
            </button>
          </div>
        </div>
        
        <div className="p-8 space-y-6 max-h-[70vh] overflow-y-auto">
          <div className="grid grid-cols-2 gap-4">
            <div className="p-4 rounded-xl bg-rose-50 dark:bg-rose-900/20 border border-rose-100 dark:border-rose-900/30">
              <p className="text-[10px] font-bold text-rose-600 uppercase mb-2">Key Risk Summary</p>
              <p className="text-sm font-medium">High divergence in Alulose limits for EU market. Potential export block without formulation adjustment.</p>
            </div>
            <div className="p-4 rounded-xl bg-amber-50 dark:bg-amber-900/20 border border-amber-100 dark:border-amber-900/30">
              <p className="text-[10px] font-bold text-amber-600 uppercase mb-2">Ingredient Gap Analysis</p>
              <p className="text-sm font-medium">3/12 ingredients require re-validation for Japan (Walnut allergen update).</p>
            </div>
          </div>

          <div className="space-y-3">
            <h4 className="text-xs font-bold text-slate-400 uppercase tracking-wider">AI-Recommended Formulation Change</h4>
            <div className="p-4 rounded-xl bg-primary/5 border border-primary/10 space-y-2">
              <div className="flex items-start gap-3">
                <CheckCircle2 className="size-4 text-primary mt-0.5" />
                <p className="text-sm">Substitute Alulose with <strong>Erythritol/Stevia blend</strong> for EU-bound batches.</p>
              </div>
              <div className="flex items-start gap-3">
                <CheckCircle2 className="size-4 text-primary mt-0.5" />
                <p className="text-sm">Add <strong>Pine Nut</strong> icon to master label for South Korea compliance.</p>
              </div>
            </div>
          </div>

          <div className="space-y-3">
            <h4 className="text-xs font-bold text-slate-400 uppercase tracking-wider">Compliance Timeline Check</h4>
            <div className="flex items-center gap-4 text-sm">
              <div className="flex items-center gap-2">
                <div className="size-2 bg-green-500 rounded-full"></div>
                <span>USA: Valid</span>
              </div>
              <div className="flex items-center gap-2">
                <div className="size-2 bg-rose-500 rounded-full"></div>
                <span>EU: Action Required (D-30)</span>
              </div>
              <div className="flex items-center gap-2">
                <div className="size-2 bg-amber-500 rounded-full"></div>
                <span>JP: Transitioning</span>
              </div>
            </div>
          </div>
        </div>

        <div className="p-6 border-t border-slate-100 dark:border-slate-800 bg-slate-50/50 dark:bg-slate-800/50 flex justify-end gap-3">
          <button onClick={onClose} className="px-4 py-2 text-sm font-bold text-slate-600 hover:bg-slate-200 dark:hover:bg-slate-700 rounded-lg transition-colors">Cancel</button>
          <button className="px-6 py-2 bg-primary text-white text-sm font-bold rounded-lg hover:bg-primary/90 transition-colors flex items-center gap-2">
            <Download className="size-4" />
            Generate Final PDF
          </button>
        </div>
      </motion.div>
    </div>
  );
};

const IngredientsSection = ({ searchQuery }: { searchQuery: string }) => {
  const ingredients = [
    { 
      name: 'Alulose', 
      kr: 'Approved (Limit 10%)', 
      us: 'GRAS (Notice No. 498)', 
      eu: 'Novel Food (Under Review)', 
      advisory: 'EU: Pending due to data insufficiency (자료 제출 미비). US: 2026 Supply Shortage Outlook (공급 부족 전망). Use as sugar substitute; monitor EU approval status for export formulations.',
      isLatest: true,
      alerts: {
        eu: 'Regulatory Barrier',
        us: 'Supply Risk'
      }
    },
    { 
      name: 'Lutein', 
      kr: 'Functional Ingredient', 
      us: 'GRAS', 
      eu: 'Approved (Health Claim)', 
      advisory: 'Ensure dosage meets specific health claim requirements in EU.',
      isLatest: true 
    },
    { 
      name: 'BCAA', 
      kr: 'Approved', 
      us: 'GRAS', 
      eu: 'Approved', 
      advisory: 'Standard amino acid profile compliance required.',
      isLatest: false 
    },
    { 
      name: 'Probiotics', 
      kr: 'Functional', 
      us: 'GRAS/NDI', 
      eu: 'QPS List', 
      advisory: 'Strain-specific documentation needed for EU QPS status.',
      isLatest: false 
    },
    { 
      name: 'HMB', 
      kr: 'Indiv. Recognized', 
      us: 'GRAS', 
      eu: 'Novel Food', 
      advisory: 'Strict purity standards apply for individually recognized status.',
      isLatest: false 
    },
  ];

  const filtered = ingredients.filter(i => 
    i.name.toLowerCase().includes(searchQuery.toLowerCase()) || 
    i.advisory.toLowerCase().includes(searchQuery.toLowerCase())
  );

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <h2 className="text-2xl font-bold flex items-center gap-3">
          <FlaskConical className="size-7 text-primary" />
          Individually Recognized Ingredients (Global)
        </h2>
      </div>

      <div className="bg-white dark:bg-slate-900 rounded-2xl border border-slate-200 dark:border-slate-800 overflow-hidden shadow-sm">
        <table className="w-full text-left border-collapse">
          <thead>
            <tr className="bg-slate-50 dark:bg-slate-800/50 border-b border-slate-200 dark:border-slate-800">
              <th className="px-6 py-4 text-xs font-bold uppercase text-slate-500">Ingredient Name</th>
              <th className="px-6 py-4 text-xs font-bold uppercase text-slate-500">South Korea (MFDS)</th>
              <th className="px-6 py-4 text-xs font-bold uppercase text-slate-500">USA (FDA GRAS)</th>
              <th className="px-6 py-4 text-xs font-bold uppercase text-slate-500">EU (EFSA Novel Food)</th>
              <th className="px-6 py-4 text-xs font-bold uppercase text-primary">R&D Advisory</th>
            </tr>
          </thead>
          <tbody className="divide-y divide-slate-100 dark:divide-slate-800">
            {filtered.map(i => (
              <tr key={i.name} className={`hover:bg-slate-50/50 dark:hover:bg-slate-800/30 transition-colors ${i.isLatest ? 'animate-pulse-row' : ''}`}>
                <td className="px-6 py-4 font-bold text-sm">
                  <div className="flex items-center gap-2">
                    {i.name}
                    {i.isLatest && (
                      <span className="px-1.5 py-0.5 bg-primary/10 text-primary text-[8px] font-black rounded uppercase tracking-tighter">Latest</span>
                    )}
                  </div>
                </td>
                <td className="px-6 py-4 text-sm">{i.kr}</td>
                <td className="px-6 py-4 text-sm">
                  <div className="flex items-center gap-2">
                    {i.us}
                    {i.alerts?.us && (
                      <div className="group relative">
                        <AlertCircle className="size-3.5 text-amber-500 cursor-help" />
                        <div className="absolute bottom-full left-1/2 -translate-x-1/2 mb-2 px-2 py-1 bg-slate-800 text-white text-[9px] rounded opacity-0 group-hover:opacity-100 transition-opacity whitespace-nowrap z-20">
                          {i.alerts.us}
                        </div>
                      </div>
                    )}
                  </div>
                </td>
                <td className="px-6 py-4 text-sm">
                  <div className="flex items-center gap-2">
                    <span className={i.eu.includes('Review') || i.eu.includes('Pending') ? 'text-amber-500 font-medium' : ''}>{i.eu}</span>
                    {i.alerts?.eu && (
                      <div className="group relative">
                        <XCircle className="size-3.5 text-rose-500 cursor-help" />
                        <div className="absolute bottom-full left-1/2 -translate-x-1/2 mb-2 px-2 py-1 bg-slate-800 text-white text-[9px] rounded opacity-0 group-hover:opacity-100 transition-opacity whitespace-nowrap z-20">
                          {i.alerts.eu}
                        </div>
                      </div>
                    )}
                  </div>
                </td>
                <td className="px-6 py-4">
                  <div className="p-2 rounded bg-primary/5 border border-primary/10 text-[11px] text-slate-600 dark:text-slate-400 leading-tight">
                    {i.advisory}
                  </div>
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    </div>
  );
};

const ComplianceSection = ({ searchQuery }: { searchQuery: string }) => {
  const complianceData = [
    {
      market: 'USA (FDA)',
      product: 'Diabetic FSMP',
      banned: 'Certain synthetic colors (Red 3 in CA), Non-GRAS sweeteners',
      certificates: 'FSVP (Foreign Supplier Verification), FSMA 204 Traceability Record',
      standard: '21 CFR 101.9 / FSMA 204',
      risk: 'High (Traceability)',
      isLatest: true
    },
    {
      market: 'EU (EFSA)',
      product: 'Diabetic FSMP',
      banned: 'Titanium Dioxide (E171), High synthetic sweetener levels in Cat 13.2',
      certificates: 'Certificate of Free Sale, Health Certificate, Novel Food Auth',
      standard: 'Regulation 609/2013 / 1169/2011',
      risk: 'Medium (Labeling)',
      isLatest: true
    },
    {
      market: 'China (SAMR)',
      product: 'FSMP',
      banned: 'Ingredients not on GB standard approved list',
      certificates: 'SAMR Registration, Factory Audit Report',
      standard: 'GB 29922 / GB 25596',
      risk: 'Critical (Registration)',
      isLatest: false
    },
    {
      market: 'Japan (MHLW)',
      product: 'Special Use Food',
      banned: 'Walnut (as undeclared allergen), specific additives',
      certificates: 'Certificate of Origin, JAS Compliance',
      standard: 'Food Sanitation Act / CAA Labeling',
      risk: 'Low (Allergen Update)',
      isLatest: false
    }
  ];

  const filtered = complianceData.filter(d => 
    d.market.toLowerCase().includes(searchQuery.toLowerCase()) || 
    d.product.toLowerCase().includes(searchQuery.toLowerCase()) ||
    d.standard.toLowerCase().includes(searchQuery.toLowerCase())
  );

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <h2 className="text-2xl font-bold flex items-center gap-3">
          <ShieldCheck className="size-7 text-primary" />
          Export & Import Compliance Matrix (Risk Matrix)
        </h2>
      </div>

      <div className="bg-white dark:bg-slate-900 rounded-2xl border border-slate-200 dark:border-slate-800 overflow-hidden shadow-sm">
        <table className="w-full text-left border-collapse">
          <thead>
            <tr className="bg-slate-50 dark:bg-slate-800/50 border-b border-slate-200 dark:border-slate-800">
              <th className="px-6 py-4 text-xs font-bold uppercase text-slate-500">Market / Region</th>
              <th className="px-6 py-4 text-xs font-bold uppercase text-slate-500">Banned Substances</th>
              <th className="px-6 py-4 text-xs font-bold uppercase text-slate-500">Required Certificates</th>
              <th className="px-6 py-4 text-xs font-bold uppercase text-slate-500">Reference Standard</th>
              <th className="px-6 py-4 text-xs font-bold uppercase text-slate-500">Risk Level</th>
            </tr>
          </thead>
          <tbody className="divide-y divide-slate-100 dark:divide-slate-800">
            {filtered.map((d, idx) => (
              <tr key={idx} className={`hover:bg-slate-50/50 dark:hover:bg-slate-800/30 transition-colors ${d.isLatest ? 'animate-pulse-row' : ''}`}>
                <td className="px-6 py-4">
                  <div className="flex items-center gap-2">
                    <span className="font-bold text-sm">{d.market}</span>
                    {d.isLatest && (
                      <span className="px-1.5 py-0.5 bg-primary/10 text-primary text-[8px] font-black rounded uppercase tracking-tighter">Latest Update</span>
                    )}
                  </div>
                  <p className="text-[10px] text-slate-500">{d.product}</p>
                </td>
                <td className="px-6 py-4 text-sm text-rose-500 font-medium max-w-xs">{d.banned}</td>
                <td className="px-6 py-4 text-sm text-slate-600 dark:text-slate-400 max-w-xs">{d.certificates}</td>
                <td className="px-6 py-4 text-sm font-mono text-slate-500">{d.standard}</td>
                <td className="px-6 py-4">
                  <span className={`px-2 py-1 rounded text-[10px] font-bold ${
                    d.risk.includes('High') || d.risk.includes('Critical') 
                      ? 'bg-rose-100 text-rose-600' 
                      : d.risk.includes('Medium') 
                        ? 'bg-amber-100 text-amber-600' 
                        : 'bg-teal-100 text-teal-600'
                  }`}>
                    {d.risk}
                  </span>
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    </div>
  );
};

const MethodologySection = () => (
  <div className="space-y-6 max-w-4xl">
    <h2 className="text-2xl font-bold flex items-center gap-3">
      <FileText className="size-7 text-primary" />
      AI-Driven Data Verification Methodology
    </h2>
    <div className="bg-white dark:bg-slate-900 p-8 rounded-2xl border border-slate-200 dark:border-slate-800 space-y-6">
      <div className="space-y-4">
        <h3 className="text-lg font-bold">NotebookLM Integration</h3>
        <p className="text-sm text-slate-600 dark:text-slate-400 leading-relaxed">
          Regu-Lens utilizes Google's <strong>NotebookLM</strong> to process and verify complex regulatory documents from MFDS, FDA, and EFSA. Our AI engine cross-references raw legal texts with historical data to ensure 99.9% accuracy in our advisory columns.
        </p>
      </div>
      <div className="grid grid-cols-3 gap-6">
        <div className="p-4 rounded-xl bg-slate-50 dark:bg-slate-800/50 border border-slate-100 dark:border-slate-800">
          <p className="text-xs font-bold text-primary uppercase mb-1">Step 1</p>
          <p className="text-sm font-bold">Source Ingestion</p>
          <p className="text-[10px] text-slate-500 mt-1">Direct PDF/URL scraping from official gov portals.</p>
        </div>
        <div className="p-4 rounded-xl bg-slate-50 dark:bg-slate-800/50 border border-slate-100 dark:border-slate-800">
          <p className="text-xs font-bold text-primary uppercase mb-1">Step 2</p>
          <p className="text-sm font-bold">Contextual Analysis</p>
          <p className="text-[10px] text-slate-500 mt-1">NotebookLM identifies specific ingredient limits and deadlines.</p>
        </div>
        <div className="p-4 rounded-xl bg-slate-50 dark:bg-slate-800/50 border border-slate-100 dark:border-slate-800">
          <p className="text-xs font-bold text-primary uppercase mb-1">Step 3</p>
          <p className="text-sm font-bold">R&D Advisory</p>
          <p className="text-[10px] text-slate-500 mt-1">AI generates actionable insights for formulation teams.</p>
        </div>
      </div>
    </div>
  </div>
);

export default function App() {
  const [isGeneralFoodOpen, setIsGeneralFoodOpen] = useState(true);
  const [isPortfolioOpen, setIsPortfolioOpen] = useState(true);
  const [activeTab, setActiveTab] = useState('dashboard');
  const [isModalOpen, setIsModalOpen] = useState(false);
  const [searchQuery, setSearchQuery] = useState('');

  const comparisonData = [
    { 
      category: "Nutritional Ratio (Carbs/Sugar)", 
      subCategory: "Diabetic FSMP Macronutrients",
      korea: "Carbs 50-60%, Protein 15-20%, Fat 20-25%. Simple sugars must be < 10% of total kcal.",
      france: "USA (FDA): No fixed ratio; must meet 'distinctive nutritional requirements' per medical evaluation (21 CFR 101.9).",
      gap: "Major Divergence",
      gapColor: "rose",
      advice: "Formulate with slow-release carbs (Isomaltulose) to maintain low GI while meeting MFDS % targets."
    },
    { 
      category: "Food Additives (Sweeteners)", 
      subCategory: "Reg 1333/2008 Cat 13.2",
      korea: "Approved list in Food Additive Code (Sucralose, Acesulfame K allowed).",
      france: "EU: Stricter mg/kg limits for synthetic sweeteners in Cat 13.2 compared to KR's Quantum Satis.",
      gap: "Moderate Divergence",
      gapColor: "amber",
      advice: "Cross-check sweetener dosages against EU Cat 13.2 specific limits (e.g., Acesulfame K max 450mg/kg)."
    },
    { 
      category: "Labeling (Allergens)", 
      subCategory: "Specified Ingredients",
      korea: "22 mandatory items including Pine nut, Buckwheat, and Peach.",
      france: "Japan: 8 mandatory (Walnut recently added) + 20 recommended items.",
      gap: "Moderate Divergence",
      gapColor: "amber",
      advice: "Update allergen statement to include 'Walnut' for JP market and verify font/layout compliance."
    },
    { 
      category: "Mandatory Warnings", 
      subCategory: "Safety Statements",
      korea: "Must state 'For patients only' and 'Use under doctor's guidance'.",
      france: "Taiwan: Must include 'Not for parenteral (IV) use' in Traditional Chinese (不得經腸道外給與).",
      gap: "Aligned",
      gapColor: "teal",
      advice: "Add mandatory Traditional Chinese warning text for Taiwan-bound diabetic products."
    }
  ];

  const filteredComparison = comparisonData.filter(row => 
    row.category.toLowerCase().includes(searchQuery.toLowerCase()) ||
    row.subCategory.toLowerCase().includes(searchQuery.toLowerCase()) ||
    row.advice.toLowerCase().includes(searchQuery.toLowerCase())
  );

  return (
    <div className="flex h-screen overflow-hidden bg-background-light dark:bg-background-dark text-slate-900 dark:text-slate-100">
      {/* Sidebar */}
      <aside className="w-72 bg-white dark:bg-slate-900 border-r border-slate-200 dark:border-slate-800 flex flex-col">
        <div className="p-6 border-b border-slate-100 dark:border-slate-800 flex items-center gap-3">
          <div className="size-10 bg-primary rounded-lg flex items-center justify-center text-white">
            <Microscope className="size-6" />
          </div>
          <div>
            <h1 className="font-bold text-xl tracking-tight text-primary">Regu-Lens</h1>
            <p className="text-[10px] uppercase tracking-widest text-slate-500 font-bold">Global Regulation Hub</p>
          </div>
        </div>

        <nav className="flex-1 overflow-y-auto p-4 space-y-2">
          <p className="text-[11px] font-bold text-slate-400 uppercase tracking-wider px-3 mb-2">Categories</p>
          <SidebarItem icon={BarChart3} label="Dashboard" active={activeTab === 'dashboard'} onClick={() => setActiveTab('dashboard')} />
          <SidebarItem icon={Stethoscope} label="FSMP (Medical Food)" />
          <SidebarItem icon={FlaskConical} label="Individually Recognized" active={activeTab === 'ingredients'} onClick={() => setActiveTab('ingredients')} />
          <SidebarItem icon={ShieldCheck} label="Export & Import Compliance" active={activeTab === 'compliance'} onClick={() => setActiveTab('compliance')} />
          <SidebarItem icon={Leaf} label="Plant-based" />

          <div className="space-y-1 mt-1">
            <button 
              onClick={() => setIsGeneralFoodOpen(!isGeneralFoodOpen)}
              className="w-full flex items-center justify-between px-3 py-2 rounded-lg text-slate-600 dark:text-slate-400 hover:bg-slate-100 dark:hover:bg-slate-800 transition-colors group"
            >
              <div className="flex items-center gap-3">
                <Utensils className="size-5" />
                <span className="text-sm font-medium">General Food</span>
              </div>
              <ChevronDown className={`size-4 transition-transform ${isGeneralFoodOpen ? 'rotate-180' : ''}`} />
            </button>
            
            {isGeneralFoodOpen && (
              <motion.div 
                initial={{ opacity: 0, height: 0 }}
                animate={{ opacity: 1, height: 'auto' }}
                className="pl-11 space-y-1"
              >
                <a href="#" className="flex items-center gap-3 px-3 py-2 rounded-lg text-slate-500 dark:text-slate-400 hover:bg-slate-100 dark:hover:bg-slate-800 transition-colors">
                  <Wheat className="size-4" />
                  <span className="text-sm">Grains & Cereals</span>
                </a>
                <a href="#" className="flex items-center gap-3 px-3 py-2 rounded-lg text-slate-500 dark:text-slate-400 hover:bg-slate-100 dark:hover:bg-slate-800 transition-colors">
                  <Drumstick className="size-4" />
                  <span className="text-sm">Meat, Fish, Eggs & Legumes</span>
                </a>
                <a href="#" className="flex items-center gap-3 px-3 py-2 rounded-lg text-slate-500 dark:text-slate-400 hover:bg-slate-100 dark:hover:bg-slate-800 transition-colors">
                  <Carrot className="size-4" />
                  <span className="text-sm">Vegetables</span>
                </a>
                <a href="#" className="flex items-center gap-3 px-3 py-2 rounded-lg text-slate-500 dark:text-slate-400 hover:bg-slate-100 dark:hover:bg-slate-800 transition-colors">
                  <Apple className="size-4" />
                  <span className="text-sm">Fruits</span>
                </a>
                <a href="#" className="flex items-center gap-3 px-3 py-2 rounded-lg text-slate-500 dark:text-slate-400 hover:bg-slate-100 dark:hover:bg-slate-800 transition-colors">
                  <Milk className="size-4" />
                  <span className="text-sm">Dairy & Milk Products</span>
                </a>
                <button 
                  onClick={() => setActiveTab('ingredients')}
                  className="w-full flex items-center gap-3 px-3 py-2 rounded-lg text-slate-500 dark:text-slate-400 hover:bg-slate-100 dark:hover:bg-slate-800 transition-colors"
                >
                  <CakeSlice className="size-4" />
                  <span className="text-sm">Bakery & Confectionery</span>
                </button>
              </motion.div>
            )}
          </div>

          <div className="pt-4 mt-4 border-t border-slate-100 dark:border-slate-800">
            <p className="text-[11px] font-bold text-slate-400 uppercase tracking-wider px-3 mb-2">Personal</p>
            <button 
              onClick={() => setIsPortfolioOpen(!isPortfolioOpen)}
              className="w-full flex items-center justify-between px-3 py-2 rounded-lg text-slate-600 dark:text-slate-400 hover:bg-slate-100 dark:hover:bg-slate-800 transition-colors group"
            >
              <div className="flex items-center gap-3">
                <FolderHeart className="size-5" />
                <span className="text-sm font-medium">My Portfolio</span>
              </div>
              <ChevronDown className={`size-4 transition-transform ${isPortfolioOpen ? 'rotate-180' : ''}`} />
            </button>
            
            {isPortfolioOpen && (
              <motion.div 
                initial={{ opacity: 0, height: 0 }}
                animate={{ opacity: 1, height: 'auto' }}
                className="pl-11 space-y-1 mt-1"
              >
                <button 
                  onClick={() => setActiveTab('methodology')}
                  className={`w-full flex items-center gap-3 px-3 py-2 rounded-lg transition-colors ${activeTab === 'methodology' ? 'bg-primary/10 text-primary' : 'text-slate-500 dark:text-slate-400 hover:bg-slate-100 dark:hover:bg-slate-800'}`}
                >
                  <FileText className="size-4" />
                  <span className="text-sm">Methodology</span>
                </button>
              </motion.div>
            )}
          </div>
        </nav>

        <div className="p-4 border-t border-slate-100 dark:border-slate-800">
          <div className="bg-primary/5 rounded-xl p-4">
            <p className="text-xs font-medium text-slate-600 dark:text-slate-400">Database Status</p>
            <div className="flex items-center gap-2 mt-1">
              <div className="size-2 bg-green-500 rounded-full animate-breathing"></div>
              <span className="text-xs font-bold text-slate-800 dark:text-slate-200">Live Updates Enabled</span>
            </div>
          </div>
        </div>
      </aside>

      {/* Main Content */}
      <main className="flex-1 flex flex-col overflow-hidden">
        {/* Header */}
        <header className="h-16 bg-white dark:bg-slate-900 border-b border-slate-200 dark:border-slate-800 px-8 flex items-center justify-between z-10">
          <div className="flex-1 max-w-2xl">
            <div className="relative">
              <Search className="absolute left-3 top-1/2 -translate-y-1/2 size-4 text-slate-400" />
              <input 
                type="text" 
                value={searchQuery}
                onChange={(e) => setSearchQuery(e.target.value)}
                className="w-full pl-10 pr-4 py-2 bg-slate-100 dark:bg-slate-800 border-none rounded-lg focus:ring-2 focus:ring-primary/50 text-sm outline-none" 
                placeholder="Search ingredients, e.g., Alulose, BCAA"
              />
            </div>
          </div>
          <div className="flex items-center gap-4 ml-8">
            <button className="p-2 text-slate-500 hover:bg-slate-100 dark:hover:bg-slate-800 rounded-lg relative">
              <Bell className="size-5" />
              <span className="absolute top-2 right-2 size-2 bg-red-500 border-2 border-white dark:border-slate-900 rounded-full"></span>
            </button>
            <div className="h-8 w-px bg-slate-200 dark:bg-slate-800"></div>
            <div className="flex items-center gap-3">
              <div className="text-right hidden sm:block">
                <p className="text-xs font-bold">Researcher Sarah Chen</p>
                <p className="text-[10px] text-slate-500">Regulatory Lead</p>
              </div>
              <div className="size-10 rounded-full bg-slate-200 overflow-hidden border-2 border-primary/20">
                <img 
                  src="https://lh3.googleusercontent.com/aida-public/AB6AXuD2VnHM7d4aEEzgni-PCUIGRNQZ7Tz8TNFmhiWPIgwKaib3AIs2tAvxQZXYbKqqX63nUk4lQwEWr0b86bjBxUQEhABmSQIbdgJWVjPrjS8uy6jHYToXrn5GPy6N8T_Vv0G4VZSC_-jqfb5R9g-W8d-K1qCNmSY89xVHqGP-wsAbuiYJs6tietrzZy2sTOWSQRnEUdxIvEkBEnP_MUH0SGndrXGp9QL4cYP_JmivnENymQ8WFUHHl3O1AiKfP3pTKn0nQVFIeCnwVON3" 
                  alt="Profile" 
                  className="w-full h-full object-cover"
                  referrerPolicy="no-referrer"
                />
              </div>
            </div>
          </div>
        </header>

        {/* Dashboard Body */}
        <div className="flex-1 overflow-y-auto p-8 space-y-8">
          {activeTab === 'dashboard' && (
            <>
              {/* Top Section: News & Map */}
              <div className="grid grid-cols-12 gap-8">
                {/* Global News Feed */}
                <div className="col-span-12 lg:col-span-3 flex flex-col gap-4">
                  <div className="flex items-center justify-between">
                    <h2 className="text-lg font-bold flex items-center gap-2">
                      <Rss className="size-5 text-primary" />
                      Global News Feed
                    </h2>
                    <button className="text-xs font-bold text-primary hover:underline">View All</button>
                  </div>
                  <div className="space-y-3">
                    <NewsCard 
                      country="KR" 
                      title="MFDS: Expansion of FSMP Standard Manufacturing Criteria" 
                      description="New categories for chronic disease-specific formulas added to the Food Standards and Specifications." 
                      time="1 hour ago" 
                      type="Regulatory Update" 
                      isNew={true}
                    />
                    <NewsCard 
                      country="US" 
                      title="FDA: Review of Medical Food Labeling Guidance" 
                      description="Proposed updates to clarify the distinction between medical foods and dietary supplements." 
                      time="4 hours ago" 
                      type="Policy Review" 
                      isNew={true}
                    />
                    <NewsCard 
                      country="EU" 
                      title="EFSA: Sweetener Level Re-evaluation for Cat 13.2" 
                      description="Updated maximum permitted levels for synthetic sweeteners in medical foods under Reg 1333/2008." 
                      time="6 hours ago" 
                      type="Safety Standard" 
                      isNew={true}
                    />
                    <NewsCard 
                      country="JP" 
                      title="CAA: Walnut Added to Mandatory Allergen List" 
                      description="Walnut is now the 8th mandatory allergen ingredient in Japan; transition period ends 2025." 
                      time="12 hours ago" 
                      type="Labeling Alert" 
                      isNew={true}
                    />
                    <NewsCard 
                      country="TW" 
                      title="TFDA: New Registration Rules for Special Nutrient Foods" 
                      description="Stricter clinical data requirements for diabetic and oncology-specific formulas imported to Taiwan." 
                      time="1 day ago" 
                      type="Import Regulation" 
                    />
                  </div>
                </div>

                {/* Compliance Timeline */}
                <div className="col-span-12 lg:col-span-3 flex flex-col gap-4">
                  <div className="flex items-center justify-between">
                    <h2 className="text-lg font-bold flex items-center gap-2">
                      <Calendar className="size-5 text-primary" />
                      Compliance Timeline
                    </h2>
                  </div>
                  <div className="bg-white dark:bg-slate-900 p-6 rounded-xl border border-slate-200 dark:border-slate-800 flex-1">
                    <div className="relative border-l-2 border-slate-100 dark:border-slate-800 ml-2 pl-6 space-y-8">
                      {(() => {
                        const events = [
                          { date: '2026.04.15', title: 'EU FSMP Labeling Change', desc: 'Mandatory front-of-pack update', urgency: 'D-30' },
                          { date: '2025.11.20', title: 'MFDS Additive Review', desc: 'Alulose concentration update' },
                          { date: '2028.07.20', title: 'FDA FSMA 204 Deadline', desc: 'Enhanced traceability compliance', urgency: 'NEW: Extended' },
                          { date: '2026.01.10', title: 'GMO Labeling Update (KR)', desc: 'New standards for processed foods' }
                        ].sort((a, b) => b.date.localeCompare(a.date));

                        const today = '2026.03.10';
                        const upcoming = events.filter(e => e.date >= today).sort((a, b) => a.date.localeCompare(b.date));
                        const mostUrgent = upcoming[0] || events[0];

                        return events.map((event, idx) => (
                          <div key={idx} className="relative">
                            <div className={`absolute -left-[31px] top-1 size-4 rounded-full border-4 border-white dark:border-slate-900 ${event === mostUrgent ? 'bg-primary' : 'bg-slate-300'}`}>
                              {event === mostUrgent && (
                                <div className="absolute -top-1 -right-1 size-2 bg-red-500 rounded-full border border-white animate-pulse"></div>
                              )}
                            </div>
                            <div className="flex items-center justify-between">
                              <p className={`text-[10px] font-bold ${event === mostUrgent ? 'text-primary' : 'text-slate-400'}`}>{event.date}</p>
                              {event.urgency && (
                                <span className="px-1.5 py-0.5 bg-rose-500 text-white text-[9px] font-black rounded italic">{event.urgency}</span>
                              )}
                            </div>
                            <p className="text-xs font-bold mt-1">{event.title}</p>
                            <p className="text-[10px] text-slate-500">{event.desc}</p>
                          </div>
                        ));
                      })()}
                    </div>
                  </div>
                </div>

                {/* Interactive Map */}
                <div className="col-span-12 lg:col-span-6 flex flex-col gap-4">
                  <div className="flex items-center justify-between">
                    <h2 className="text-lg font-bold flex items-center gap-2">
                      <Globe className="size-5 text-primary" />
                      Regulation Heatmap
                    </h2>
                    <div className="flex gap-3">
                      <div className="flex items-center gap-1.5 text-[10px] font-bold text-slate-500">
                        <div className="size-2 rounded-full bg-red-500"></div> Strict
                      </div>
                      <div className="flex items-center gap-1.5 text-[10px] font-bold text-slate-500">
                        <div className="size-2 rounded-full bg-yellow-500"></div> Moderate
                      </div>
                      <div className="flex items-center gap-1.5 text-[10px] font-bold text-slate-500">
                        <div className="size-2 rounded-full bg-green-500"></div> Flexible
                      </div>
                    </div>
                  </div>
                  <div className="bg-white dark:bg-slate-900 rounded-xl border border-slate-200 dark:border-slate-800 h-[420px] relative overflow-hidden group">
                    <div className="absolute inset-0 bg-slate-50 dark:bg-slate-950 flex items-center justify-center">
                      <img 
                        src="https://lh3.googleusercontent.com/aida-public/AB6AXuC1HBlQ8hA65QO1W9HIZ0leccab_BPCjVHLpg3t5fvhWbhDG0tnUPmFuCU8ts8jP3zzOOMhR-lWLosYKokdJlRlPFw9hLQjiEF1ISgPkoAijg_iDhJGpI06TZS4YU5bsY2BzZAYG7Xq9UEXwFTpy0CrGxtgvc42qvvVTf81Xj7FMoGF7bkVkKoxmfE2c3ofjxwEK__d6Y0wE3x_dfwIERqK9E3AGbsTBapnssoK84oJWfI4GmHIt0FU1KJ_beQ1EBHEN1sPVvKU0i7o" 
                        alt="World Map Heatmap" 
                        className="w-full h-full object-cover opacity-60"
                        referrerPolicy="no-referrer"
                      />
                      <div className="absolute inset-0 bg-gradient-to-t from-white dark:from-slate-900 via-transparent to-transparent opacity-40"></div>
                    </div>
                    
                    {/* Map Overlays */}
                    <div className="absolute top-1/2 left-[78%] -translate-x-1/2 -translate-y-1/2 flex items-center justify-center">
                      <div className="relative">
                        <motion.div 
                          initial={{ opacity: 0, y: 10 }}
                          animate={{ opacity: 1, y: 0 }}
                          className="absolute -top-14 left-0 bg-white dark:bg-slate-800 shadow-xl rounded-lg p-3 border border-primary/20 whitespace-nowrap"
                        >
                          <p className="text-[10px] font-bold text-primary">South Korea</p>
                          <p className="text-[9px] text-slate-500">Active Alert: Alulose</p>
                        </motion.div>
                        <div className="size-4 bg-primary rounded-full animate-ping opacity-75"></div>
                        <div className="size-3 bg-primary rounded-full absolute top-0.5 left-0.5 border-2 border-white"></div>
                      </div>
                    </div>

                    <div className="absolute bottom-4 right-4">
                      <button 
                        onClick={() => setIsModalOpen(true)}
                        className="px-4 py-2 bg-primary text-white text-xs font-bold rounded-lg flex items-center gap-2 hover:bg-primary/90 transition-colors shadow-lg"
                      >
                        <BarChart3 className="size-4" />
                        Download R&D Impact Report (PDF)
                      </button>
                    </div>
                  </div>
                </div>
              </div>

              {/* Bottom Section: Comparison Table */}
              <div className="flex flex-col gap-4">
                <div className="flex items-center justify-between">
                  <h2 className="text-lg font-bold flex items-center gap-2">
                    <ArrowLeftRight className="size-5 text-primary" />
                    Regulation Standard Comparison: Korea vs France
                  </h2>
                  <div className="flex items-center gap-4">
                    <div className="flex items-center gap-3">
                      <label className="text-xs font-bold text-slate-500">Select Country to Compare:</label>
                      <select className="text-xs font-bold border-slate-200 dark:border-slate-800 rounded-lg bg-white dark:bg-slate-900 py-1.5 pl-3 pr-8 focus:ring-primary/50 outline-none">
                        <option>France (ANSES/EFSA)</option>
                        <option>USA (FDA)</option>
                        <option>China (SAMR)</option>
                        <option>Japan (MHLW)</option>
                      </select>
                    </div>
                    <button 
                      onClick={() => setIsModalOpen(true)}
                      className="px-4 py-1.5 bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-lg text-xs font-bold flex items-center gap-2 hover:bg-slate-50 dark:hover:bg-slate-800 transition-colors"
                    >
                      <Download className="size-4" />
                      Export PDF
                    </button>
                  </div>
                </div>

                <div className="bg-white dark:bg-slate-900 rounded-xl border border-slate-200 dark:border-slate-800 overflow-hidden">
                  <table className="w-full text-left border-collapse">
                    <thead>
                      <tr className="bg-slate-50 dark:bg-slate-800/50 border-b border-slate-200 dark:border-slate-800">
                        <th className="px-6 py-4 text-xs font-bold uppercase tracking-wider text-slate-500">Regulation Category</th>
                        <th className="px-6 py-4 text-xs font-bold uppercase tracking-wider text-slate-500">South Korea (MFDS)</th>
                        <th className="px-6 py-4 text-xs font-bold uppercase tracking-wider text-slate-500">France (ANSES/EFSA)</th>
                        <th className="px-6 py-4 text-xs font-bold uppercase tracking-wider text-slate-500">Status Gap</th>
                        <th className="px-6 py-4 text-xs font-bold uppercase tracking-wider text-primary">R&D Action (AI)</th>
                      </tr>
                    </thead>
                    <tbody className="divide-y divide-slate-100 dark:divide-slate-800">
                      {filteredComparison.map((row, idx) => (
                        <ComparisonRow 
                          key={idx}
                          category={row.category}
                          subCategory={row.subCategory}
                          korea={row.korea}
                          france={row.france}
                          gap={row.gap}
                          gapColor={row.gapColor}
                          advice={row.advice}
                        />
                      ))}
                    </tbody>
                  </table>
                </div>
              </div>
            </>
          )}

          {activeTab === 'ingredients' && <IngredientsSection searchQuery={searchQuery} />}
          {activeTab === 'compliance' && <ComplianceSection searchQuery={searchQuery} />}
          {activeTab === 'methodology' && <MethodologySection />}
        </div>
      </main>

      <ReportSummaryModal isOpen={isModalOpen} onClose={() => setIsModalOpen(false)} />
    </div>
  );
}

const ComparisonRow = ({ category, subCategory, korea, france, gap, gapColor, advice }: any) => {
  const colorClasses: any = {
    amber: 'bg-amber-50 text-amber-600 border-amber-200',
    rose: 'bg-rose-50 text-rose-600 border-rose-200',
    teal: 'bg-teal-50 text-teal-600 border-teal-200'
  };

  return (
    <tr className="hover:bg-slate-50/50 dark:hover:bg-slate-800/30 transition-colors">
      <td className="px-6 py-4">
        <p className="text-sm font-bold">{category}</p>
        <p className="text-[10px] text-slate-500">{subCategory}</p>
      </td>
      <td className="px-6 py-4 text-sm text-slate-600 dark:text-slate-400 leading-relaxed">{korea}</td>
      <td className="px-6 py-4 text-sm text-slate-600 dark:text-slate-400 leading-relaxed">{france}</td>
      <td className="px-6 py-4">
        <span className={`px-2 py-1 rounded border text-[10px] font-bold whitespace-nowrap ${colorClasses[gapColor]}`}>
          {gap}
        </span>
      </td>
      <td className="px-6 py-4">
        <div className="p-3 rounded bg-primary/5 border border-primary/10">
          <div className="flex items-center gap-1.5 mb-1">
            <AlertCircle className="size-3 text-primary" />
            <p className="text-[10px] font-bold text-primary italic underline">R&D Advisory:</p>
          </div>
          <p className="text-[10px] text-slate-600 dark:text-slate-400 leading-tight">{advice}</p>
        </div>
      </td>
    </tr>
  );
};
